### ISSUE TITLE
Failed build on macOS M1

### ISSUE THREAD

**Issue by schpaa** [Enerccio/SLT#16]
BUILD FAILED in 2m 50s

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'slt'.
> Could not create task ':signPlugin'.
   > ./signcerts/chain.crt (No such file or directory)

**Comment by Enerccio** [comment]
hmm, I suppose I have to add try catch ignore around there if there is no cert

**Comment by Enerccio** [comment]
Should be fixed in master
