### ISSUE TITLE
Changing the Quicklisp path fails

### ISSUE THREAD

**Issue by bit-fu** [Enerccio/SLT#18]
Using Rider on macOS Ventura with the downloaded `slt-0.1.0-signed-RD.zip`.

I go to **Settings > SLT Configuration** and change the **Quicklisp path** to `~/etc/quicklisp/setup.lisp` (my quicklisp install). When I click the **Save** button, I get an alert:

Failed to Start SBCL
Cannot invoke "com.en_circle.slt.plugin.swank.SwankClient.close()" because "this.client" is null

And the new Quicklisp path isn't saved, either.
I have entered the full path to my **SBCL executable**, which is being saved correctly.

**Comment by Enerccio** [comment]
Try new 0.1.1 version, it should be fixed!
