### ISSUE TITLE
Support for Roswell ?

### ISSUE THREAD

**Issue by Mr-Dispatch** [Enerccio/SLT#23]
While downloading & setting up SBCL (+quicklisp) has some value, it won't get one as far on windows.
Some sweet packages depend on gcc or some libs being available, and that means MSYS and a whole bunch of messing around.

Supporting Roswell (and launching it through the MSYS it's able to install -- so all the goodies would be "on path") would make it even easier for noobs to get started on windows.

**Comment by Mr-Dispatch** [comment]
> I have never heard of roswell.

Easy to rectify: https://roswell.github.io/
It's a "Lisp implementation manager", capable to download binary or to compile source distributions of multiple common lisps. It installs quicklisp by default, you can ask it to install sly/slime (AFAIR you use swank), and on windows you can ask it to install MSYS (or, if you ask for SBCL from sources, which you should - to get SBCL source-paths right, it installs MSYS automatically).

It also functions a a launcher/switcher for those installed CL impls (multiple versions of same impl. are supported).

Check it out, unless one is hell-bent on using Nix or Guix (no way on native windows, AFAIK), Roswell rocks, and it's IMO the perfect substrate to grow on.

> How do you think Roswell should be integrated?

As an implementation/quicklisp/swank installer, as an implementation switcher/chooser.

Of course, the option to launch whatever directly should always stay.

**Comment by Enerccio** [comment]
I thought sbcl had executable compiled for windows?

**Comment by Enerccio** [comment]
I mean if it has cli interface that I can call directly I could use it to download everything when setting up SDK

**Comment by Mr-Dispatch** [comment]
Not always. 2.0.0 was available, then a long silence, then some 2.0.10? came ?
Roswell download the last binary by default, and you can request to install from sources (which needs some lisp to build the image, and SBCL is probably the fastest one to be able to do it). As I said, installation from sources is preferred, cause then the immage has correct paths to sources == you can navigate to source code of built-ins.

And exactly, it has a command-line interface to do all this, so check out the home page already ;-)))

**Comment by Enerccio** [comment]
The issue is how to get roswell directly for windows user :)

**Comment by Mr-Dispatch** [comment]
Roswell gives you binaries, or (another "can of worms"), you can use ie. scoop to install it.

**Comment by Enerccio** [comment]
I will check it out when dealing with SDK since it would make my life easier, maybe. But for now I want to support SBCL only from lisp implementations (mainly due to changes to swank I did that work only on sbcl). Later, of course, I want other swank supported lisps to work. :)

**Comment by Mr-Dispatch** [comment]
Sure, no pressure from me, I'm able to do it on my own, and "nearly happy" with emacs.
Just thinking of the noobs.

Keep on the good work, perhaps in time you can massage IntelliJ into "close enough to emacs functionality, and the GUI doesn't suck as much" state.

Now seriously, though, do you think the IntelliJ type-inference framework (propped-up by a lot of work, I expect) could improve upon what we have with i.e. SBCL ?

**Comment by Mr-Dispatch** [comment]
Btw, you could even/initially outsource the installation of Roswell to the user, and just take path to the executable.
But yeah, for now the focus needs to be elsewhere.

**Comment by Mr-Dispatch** [comment]
PS: When/If you'll need someone to help you debug Roswell integration, I have:

- Two win machines; one with a fully functioning Roswell install (that I'm not willing to fuck-up; to possibly test integration), and one without (I use it to test app deployments; we might use it for "does this install functioning Roswell").

- And enough of bandwidth to re-install Roswell&MSYS over and over.  Needed to, a "few" times ;-)))

**Comment by mayerrobert** [comment]
@Enerccio just FYI: "http://www.sbcl.org/ -> Downloads" has the latest Windows64 installers for sbcl 2.3.0 (and also an installer for 32bit Windows) as well as binary packages for Linux.

This is actually a link to https://sourceforge.net/projects/sbcl/files/sbcl/ which has Windows installers for all sbcl versions including the currently latest Windows 64bit installer [sbcl-2.3.0-x86-64-windows-binary.msi](https://sourceforge.net/projects/sbcl/files/sbcl/2.3.0/sbcl-2.3.0-x86-64-windows-binary.msi/download)

You may want to replace/ amend

2. [Steel Bank Common Lisp](https://www.sbcl.org/) installed

in your README by something like

2. [Steel Bank Common Lisp](https://www.sbcl.org/) installed (go to "[https://www.sbcl.org](https://www.sbcl.org/) -> Downloads" to download a Windows installer or Linux precompiled binary distribution)

**Comment by Enerccio** [comment]
I am not sure how I can use `roswell` to install sbcl to specific folder?

**Comment by Enerccio** [comment]
Basic support (`ros run` for instance) added in #cd2ab3e7

**Comment by Enerccio** [comment]
Basic roswell support is working, if you need something specific please make new issue :)
