### ISSUE TITLE
start method in SwankServer doesn't seem to work on windows (\ VS / in windows paths)

### ISSUE THREAD

**Issue by drigoor** [Enerccio/SLT#24]
Using Intellij Community and sbcl 2.3.0 from scoop package manager (and installed initially the 'swank' and 'eclector' from quicklisp).

Modifying:
new InitScriptTemplate(...)
with
sltCore.getAbsolutePath().replace("\\", "/")
worked

See:
src/main/java/com/en_circle/slt/plugin/swank/SwankServer.java

But this doesn't seem to be a portable (clean or nice) way of doing it.

**Comment by hardliner66** [comment]
I'm not sure if it's the same problem, but I get an error on windows too:

Thats the output of Standard Output:
```lisp
Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY   ] Retry EVAL of current toplevel form.
  1: [CONTINUE] Ignore error and continue loading file "C:\\Users\\steve\\AppData\\Local\\Temp\\startServer7403874745060564102.cl".
  2: [ABORT   ] Abort loading file "C:\\Users\\steve\\AppData\\Local\\Temp\\startServer7403874745060564102.cl".
  3:            Ignore runtime option --load "startServer7403874745060564102.cl".
  4:            Skip rest of --eval and --load options.
  5:            Skip to toplevel READ/EVAL/PRINT loop.
  6: [EXIT    ] Exit SBCL (calling #'EXIT, killing the process).

(LOAD "C:SERSSTEVEAPPDATAocaltempslt12359172121097310567.cl" :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST :ERROR :EXTERNAL-FORMAT :DEFAULT)
0] 
```

That's the output of Error Output:
```
While evaluating the form starting at line 7, column 0
  of #P"C:/Users/steve/AppData/Local/Temp/startServer7403874745060564102.cl":

debugger invoked on a SB-INT:SIMPLE-FILE-ERROR in thread
#<THREAD "main thread" RUNNING {1001DC00A3}>:
  Couldn't load "C:SERSSTEVEAPPDATAocaltempslt12359172121097310567.cl": file
  does not exist.
```

**Comment by drigoor** [comment]
Yes, it's the same thing.

I just replaced this:
`String startScriptTemplate = new InitScriptTemplate(configuration, sltCore.getAbsolutePath()).render();`
-- to this -->
`String startScriptTemplate = new InitScriptTemplate(configuration, sltCore.getAbsolutePath().replace("\\", "/")).render();`
and works

ps: looking at the rest of the code, maybe the change should be something like this "StringUtils.replace(<something>, "\\", "\\\\");"

**Comment by hardliner66** [comment]
I think normal slashes should work on linux and windows. So the first fix would be correct. Could you prepare a pull request?

**Comment by Enerccio** [comment]
I see, the issue is that sbcl can't handle the windows path. Lol.

**Comment by Enerccio** [comment]
actually, it should work just fine, the issue is escaping since it's being inserted into a template

**Comment by Enerccio** [comment]
Could you test `stable` with fix?

**Comment by Enerccio** [comment]
released it as part of 0.2.0, should work out of box

**Comment by drigoor** [comment]
Problem persists.

It looks like the variable `sltCorePath` (in SltSBCLEnvironment.java) contains "\".

But the following if (in the same file)
`if (sltCorePath.contains("//"))`
maybe it should be
`if (sltCorePath.contains("\\"))`

It did worked for me in Windows

**Comment by Enerccio** [comment]
try https://github.com/Enerccio/SLT/releases/tag/v0.2.1 



... I will have to install my development on windows, won't I? :'( 
jk

**Comment by Enerccio** [comment]
if it works, could you test out if evaluating file works correctly?

**Comment by drigoor** [comment]
It works, the sbcl starts ok.

I can evaluate, in the file open, and by right click in the menu the several options available - but i see no result being displayed in the "Standard Output" (for example, `(format t "hello~%")` it is displayed "hello", but if i evaluate `(+ 1 2)` it only shows: "; processing (+ 1 ...)").

But can no longer evaluate the file by right click in the "Project" tool window (there is no longer any option for that) - but i can live with that - i prefer keybindings.

> ... I will have to install my development on windows, won't I? :'(
No problem, i can test in windows - maybe i will learn something :) the upside down is that i'll bug you with issues :P

**Comment by Enerccio** [comment]
> I can evaluate, in the file open, and by right click in the menu the several options available - but i see no result being displayed in the "Standard Output" (for example, (format t "hello~%") it is displayed "hello", but if i evaluate (+ 1 2) it only shows: "; processing (+ 1 ...)").

Standard evaluation from menu discards result by default. Would you prefer it did not? I could add a message box where those results would be displayed (probably not stdout though).

> But can no longer evaluate the file by right click in the "Project" tool window (there is no longer any option for that) - but i can live with that - i prefer keybindings. 

That seems like a different bug then. It should show up same as if you open it in editor and right click - evaluate file.

**Comment by Enerccio** [comment]
Fixed it, but won't release fix yet. If you want you can grab it off `stable` branch.
