### ISSUE TITLE
Error occured in typing to REPL

### ISSUE THREAD

**Issue by tamamu** [Enerccio/SLT#55]
Hi,

I have encountered an error as in screenshot with IntelliJ IDEA 2022.3.2 (Community Edition) on Arch Linux.
My SDK settings are below: 
- SBCL executable: `ros run`
- SBCL core (optional): `(empty)`
- Quicklisp path: `(home directory)/.roswell/lisp/quicklisp/setup.lisp`

## How to reproduce

1. Open REPL from Lisp Process tab.
2. Type something. (I was trying to require some package.)

![image](https://user-images.githubusercontent.com/9401982/218306695-9d63612b-68b9-4820-9787-b6820bf9ec08.png)

I like this project, thanks!

**Comment by Enerccio** [comment]
This is very strange. Is this first install? I installed intellij community, loaded plugin in new workspace and everything works. Can you copy ifrom from stdout, stderr and Slime Log? Also, can you zip this folder: `~/.config/JetBrains/.slt`, alternatively you can delete it and try again.

**Comment by tamamu** [comment]
Sorry I'm late to response, but it has resolved by restart the IDE!
