### ISSUE TITLE
Cannot Verify SDK

### ISSUE THREAD

**Issue by mclark-tascet** [Enerccio/SLT#67]
I cannot add a new SDK (in this case SBCL). I receive an error during verification, and cannot proceed. 

- Windows 10
- PyCharm 2023.1 (professional edition)
- Using v 0.5.0 of the plugin. 

```pwsh
PS C:\Users\macke> sbcl --version
SBCL 2.3.2
```

Installed with Chocolatey. Downloaded quicklisp file [from the website. ](https://www.quicklisp.org/beta/).

![image](https://user-images.githubusercontent.com/86391735/229388962-4e978dd7-f8fa-4bd1-b345-6455a931f63a.png)

**Comment by Enerccio** [comment]
I'll check it out.

**Comment by Enerccio** [comment]
Wait, I think I know what the issue can be. Quicklisp, if you are installing it manually, needs to be installed. You do not just download and use the file. Check https://github.com/Enerccio/SLT/wiki/User-Guide#manual-installation
