### ISSUE TITLE
Rainbow Delimiters Support

### ISSUE THREAD

**Issue by olnw** [Enerccio/SLT#69]
It would be nice to have rainbow delimiters in SLT. For me, this is a crucial visual aid for Lisp programming.

There is a [Rainbow Brackets](https://github.com/izhangzhihao/intellij-rainbow-brackets) plugin for JetBrains IDEs, but it doesn't seem to support Common Lisp, and the plugin itself costs money.

**Comment by Enerccio** [comment]
SLT uses custom highlight to show parenthesis. I wonder if I can cook up some custom solution for this.

**Comment by Enerccio** [comment]
Implemented

**Comment by Enerccio** [comment]
It looks like this: https://i.imgur.com/6nrrVmt.png

**Comment by olnw** [comment]
Great job :) Is it possible to adjust the colours for each depth of parentheses? I think this is important, in order to maintain high enough contrast when using different IDE colour schemes. Also because some people might not like the default colours. (Although I think they're fine.)

For example, [rainbow-delimiters](https://github.com/Fanael/rainbow-delimiters#customization) for Emacs allows you to customise depths 1-9, with 1 being the outermost colour.

**Comment by Enerccio** [comment]
Hmm, I suppose I can have a setting for range of colors used. I generate it as HSV 0.0-1.0 so technically there can be other range than 0.0-1.0 so you could set up your own range. Would that be enough?

**Comment by olnw** [comment]
I think there is a problem with generating colours in this way, but I could be wrong. The colour difference between each depth of parenthesis will be consistent (which is good), but each parenthesis colour will not necessarily have sufficient contrast with the background colour. Protesilaos Stavrou [took this into consideration](https://protesilaos.com/codelog/2020-12-27-modus-themes-review-rainbow-delimiters/) when choosing the parenthesis colours for his Emacs themes.

Allowing for the user to select a custom range might be helpful, but I think this problem would still remain. Perhaps a better solution is to pre-define colours for some number of depths (say, 10), and to make these colours user-customisable. There could also be an option to limit the number of colours to something less than ten.

I would also like to ask: what number of colours does this implementation use? Do the colours cycle for each level of nesting (eg. red, green, blue, red, green, ...) or will each level have its own unique colour?

BTW I think the current implementation is fine, and is totally an improvement over not having rainbow parentheses.

**Comment by Enerccio** [comment]
I parse the source file, get corresponding parenthesis and get max nesting number. Then I split 1.0 float into same intervals and use that as source to HSV. https://github.com/Enerccio/SLT/blob/fe81c422e4f5413e3d97907538616f9948790239/src/main/java/com/en_circle/slt/plugin/highlights/annotators/RainbowAnnotator.java#L85

**Comment by olnw** [comment]
All right, I think your current implementation is fine. Thank you for implementing it so quickly.
