### ISSUE TITLE
CLHS hyperspec not readable with a dark theme

### ISSUE THREAD

**Issue by DanEEStar** [Enerccio/SLT#72]
Hi, first of all thanks for this plugin. My first impression is very good!

I have this problem with the CLHS hyperspec tab. With a dark theme the background is also dark and I cannot read it.
Using a light theme makes also the hyperspec background light.

Is there a way to enforce a light theme for CLHS like in your screenshot in the guide?
Another thing: Is there a possibility to increase the font size for CLHS?

<img width="873" alt="image" src="https://user-images.githubusercontent.com/1432939/236701064-212db5ea-b874-4f0f-b27c-c25fa4d90110.png">

**Comment by Enerccio** [comment]
I will investigate

**Comment by Enerccio** [comment]
Is that true black theme from https://plugins.jetbrains.com/plugin/19348-true-black ?

**Comment by Enerccio** [comment]
Because hyperspec is correct in darcula on linux[no mac to test on :(]. I will try to investigate more

**Comment by Enerccio** [comment]
I implemented mode switching for the browser but it does nothing on my side because CLHS does not support dark themes at all, so it's a bit mystery why does it show it like that for you...

**Comment by Enerccio** [comment]
I implemented the zoom at least

**Comment by Enerccio** [comment]
Closing for the second issue. If first issue persist then remake the issue but no idea how to test it since I am do not have mac os x
