### ISSUE TITLE
Instruction for the MacOS installation for the wiki

### ISSUE THREAD

**Issue by chlebik** [Enerccio/SLT#90]
Hi!

I'm not able to edit wiki, or create PR against it, so here's the instruction of the whole setup that worked on my Mac. I've written it already in MarkDown format, but feel free to tweak/change/reformat.

Installing SBCL with QuickLisp is pretty straightforward. The instructions below worked for me without any troubles, and no troubleshooting was necessary.

* Install *SBCL* by simply using *brew*

```bash
brew install sbcl
```

* Second step is to install *QuickLisp*. The [official site](https://www.quicklisp.org/beta/#installation) has a detailed instruction just for 
MacOS users. Below I'm presenting the steps I've taken to install it.

```bash
curl -O https://beta.quicklisp.org/quicklisp.lisp       # Best way is to download to your home directory
curl -O https://beta.quicklisp.org/quicklisp.lisp.asc
gpg --verify quicklisp.lisp.asc quicklisp.lisp          # Did not work due to missing gpg command, but that's not critical
sbcl --load quicklisp.lisp                                       
```

After issuing last command REPL is opened, and installation is as simple as just following the instructions. The ones that are mentioned in the Windows installation section seems to be exactly the same as for MacOS.

* In order to setup the plugin you need to add *SBCL* to the list of the existing SDKs, the same way as in the Windows installation steps. **IMPORTANT!** Even after I've added *SBCL* executables to the config, provided *QuickLisp* path, verifying the  whole thing, Intellij still did not was able to see the SDK in the toolbar or specific SDK config. I had to restart  IDE in order for it to refresh the list. After that, *SBCL* is present in the SDK lists, and can be chosen as a default one.

**Comment by Enerccio** [comment]
https://github.com/Enerccio/SLT/wiki/User-Guide#user-submitted-guide-from-chlebik
